mastodon:
  access_token: "your_access_token"
  api_base_url: "https://mastodon.social"
user_profile:
  interests: ["технологии", "ИИ", "игры"]
  post_frequency: 1.0  # Посты в день (среднее)
  style: "неформальный"
llm:
  model: "gpt-4o"
  temperature: 0.7
  max_tokens: 200